#!/bin/bash
set -ex


PAC=_PACKAGE_
ENV=_ENV_


file=/home/ayush.bhatnagar
main_folder=main_script

#removing existing file and folder
rm -rf /home/ayush.bhatnagar/$main_folder

cp -r /usr/share/$PAC/lib/$main_folder /home/ayush.bhatnagar/ #because after installation our repo gets copied here on a machine

#cron setup #this step is required otherwise the crons will not run due to permission issue.
CRON_PKG_DIR="/etc/cron.d"
chown -Rv root:root $CRON_PKG_DIR

if [ "$ENV" == "neo-ctr" ]; then
    touch $file/neo_CTR
elif [ "$ENV" == "neo-cvr" ]; then
    touch $file/neo_CVR
else
    touch $file/something
fi

chown -R ayush.bhatnagar:Tech /home/ayush.bhatnagar/
