#!/bin/bash
set -ex


#cron setup
#CRON_PKG_DIR="/etc/cron.d"
#chown -Rv root:root $CRON_PKG_DIR

PAC=_PACKAGE_

touch /home/ayush.bhatnagar/dummy_file
cp -r /usr/share/$PAC/lib/* /home/ayush.bhatnagar/ #because after installation our repo gets copied here on a machine
